/**
 * C++ Container Fuzz Tests
 *
 * Generated by /concept.fuzz cpp hard containers 10 on 2026-03-13.
 * Agent A (isolated) generated 10 programs; Agent B verified roundtrip.
 *
 * Results:
 * - fuzz_6 (vector-only): PASS (P1 stable, vector concepts correct)
 * - fuzz_1 (nested vector): EXPECTED_DEGRADATION (initializer lists not supported)
 * - fuzz_2-5, 7-10: EXPECTED_DEGRADATION (stack/queue/map/set not yet implemented)
 */
import { describe, it, expect, beforeAll } from 'vitest'
import { Parser, Language } from 'web-tree-sitter'
import { createTestLifter } from '../helpers/setup-lifter'
import type { Lifter } from '../../src/core/lift/lifter'
import { registerCppLanguage } from '../../src/languages/cpp/generators'
import { generateCode } from '../../src/core/projection/code-generator'
import { setupTestRenderer } from '../helpers/setup-renderer'
import type { StylePreset } from '../../src/core/types'
import type { SemanticNode } from '../../src/core/semantic-tree'

const style: StylePreset = {
  id: 'apcs',
  name: { 'zh-TW': 'APCS', en: 'APCS' },
  io_style: 'cout',
  naming_convention: 'camelCase',
  indent_size: 4,
  brace_style: 'K&R',
  namespace_style: 'using',
  header_style: 'individual',
}

let tsParser: Parser
let lifter: Lifter

beforeAll(async () => {
  await Parser.init({
    locateFile: (scriptName: string) => `${process.cwd()}/public/${scriptName}`,
  })
  tsParser = new Parser()
  const lang = await Language.load(`${process.cwd()}/public/tree-sitter-cpp.wasm`)
  tsParser.setLanguage(lang)
  lifter = createTestLifter()
  registerCppLanguage()
  setupTestRenderer()
})

function liftCode(code: string): SemanticNode | null {
  const tree = tsParser.parse(code)
  return lifter.lift(tree.rootNode as any)
}

function roundTripCode(code: string): string {
  const tree = liftCode(code)
  expect(tree).not.toBeNull()
  return generateCode(tree!, 'cpp', style)
}

function collectConcepts(node: SemanticNode | null, result: Set<string> = new Set()): Set<string> {
  if (!node) return result
  result.add(node.concept)
  for (const children of Object.values(node.children ?? {})) {
    for (const child of children as SemanticNode[]) {
      collectConcepts(child, result)
    }
  }
  return result
}

describe('C++ Container Fuzz Tests', () => {

  // ─── fuzz_6: vector partition with back/pop_back/empty/push_back/size ───
  // PASS — P1 stable, all vector concepts correctly lifted and generated
  // Note: initializer list lost (known limitation), but vector operations are correct

  describe('fuzz_6: vector partition (back/pop_back/empty)', () => {
    const code = `vector<int> source;
vector<int> evens;
vector<int> odds;
cout << "Source size before: " << source.size() << endl;
while (!source.empty()) {
    int val = source.back();
    source.pop_back();
    if (val % 2 == 0) {
        evens.push_back(val);
    } else {
        odds.push_back(val);
    }
}
cout << "Source size after: " << source.size() << endl;
cout << "Source empty: " << (source.empty() ? "true" : "false") << endl;
cout << "Evens (reversed):";
for (int x : evens) {
    cout << " " << x;
}
cout << endl;
cout << "Odds (reversed):";
for (int x : odds) {
    cout << " " << x;
}
cout << endl;
cout << "Even count: " << evens.size() << endl;
cout << "Odd count: " << odds.size() << endl;`

    it('should lift all vector concepts', () => {
      const tree = liftCode(code)
      expect(tree).not.toBeNull()
      const concepts = collectConcepts(tree)
      expect(concepts.has('cpp_vector_declare')).toBe(true)
      expect(concepts.has('cpp_vector_back')).toBe(true)
      expect(concepts.has('cpp_vector_pop_back')).toBe(true)
      expect(concepts.has('cpp_vector_empty')).toBe(true)
      expect(concepts.has('cpp_vector_push_back')).toBe(true)
      expect(concepts.has('cpp_vector_size')).toBe(true)
    })

    it('should survive P1 structural equivalence', () => {
      const output = roundTripCode(code)
      const tree2 = liftCode(output)
      expect(tree2).not.toBeNull()
      const concepts2 = collectConcepts(tree2)
      expect(concepts2.has('cpp_vector_declare')).toBe(true)
      expect(concepts2.has('cpp_vector_back')).toBe(true)
      expect(concepts2.has('cpp_vector_pop_back')).toBe(true)
      expect(concepts2.has('cpp_vector_empty')).toBe(true)
      expect(concepts2.has('cpp_vector_push_back')).toBe(true)
      expect(concepts2.has('cpp_vector_size')).toBe(true)
    })

    it('should generate correct vector method calls', () => {
      const output = roundTripCode(code)
      expect(output).toContain('.back()')
      expect(output).toContain('.pop_back()')
      expect(output).toContain('.empty()')
      expect(output).toContain('.push_back(')
      expect(output).toContain('.size()')
    })
  })

  // ─── fuzz_1: nested vector matrix transpose ───
  // EXPECTED_DEGRADATION — initializer list `= {{1,2,3},{4,5,6}}` and constructor args
  // `(cols, vector<int>(rows))` not supported. Vector declared as empty.

  describe('fuzz_1: nested vector (initializer list degradation)', () => {
    const code = `vector<vector<int>> matrix;
int rows = matrix.size();
int cols = matrix[0].size();
cout << rows << endl;`

    it('should lift nested vector<vector<int>> declare', () => {
      const tree = liftCode(code)
      expect(tree).not.toBeNull()
      const concepts = collectConcepts(tree)
      expect(concepts.has('cpp_vector_declare')).toBe(true)
    })

    it('should generate vector<vector<int>> declaration', () => {
      const output = roundTripCode(code)
      expect(output).toContain('vector<vector<int>>')
    })
  })

  // ─── fuzz_2: stack expression evaluator ───
  // EXPECTED_DEGRADATION — stack concepts now implemented, but program uses
  // string array initializer list and istringstream which are not supported.
  // Stack operations (push/pop/top) ARE correctly lifted.

  it.todo('fuzz_2: stack expression evaluator — needs array initializer list and istringstream support')

  // ─── stack fuzz: bracket matching (stack-only, P1 stable) ───

  describe('stack fuzz: bracket matching (stack concepts only)', () => {
    const code = `stack<char> st;
string s = "([{}])";
for (char c : s) {
    if (c == '(' || c == '[' || c == '{') {
        st.push(c);
    }
}
cout << st.top() << endl;
st.pop();
cout << st.top() << endl;
st.pop();
cout << st.top() << endl;
cout << st.empty() << endl;`

    it('should lift stack declare, push, top, pop', () => {
      const tree = liftCode(code)
      expect(tree).not.toBeNull()
      const concepts = collectConcepts(tree)
      expect(concepts.has('cpp_stack_declare')).toBe(true)
      expect(concepts.has('cpp_stack_push')).toBe(true)
      expect(concepts.has('cpp_stack_top')).toBe(true)
      expect(concepts.has('cpp_stack_pop')).toBe(true)
    })

    it('should survive P1 structural equivalence', () => {
      const output = roundTripCode(code)
      const tree2 = liftCode(output)
      expect(tree2).not.toBeNull()
      const concepts2 = collectConcepts(tree2)
      expect(concepts2.has('cpp_stack_declare')).toBe(true)
      expect(concepts2.has('cpp_stack_push')).toBe(true)
      expect(concepts2.has('cpp_stack_top')).toBe(true)
      expect(concepts2.has('cpp_stack_pop')).toBe(true)
    })
  })

  // ─── fuzz_3: map frequency counter with erase ───
  // EXPECTED_DEGRADATION — cpp_map_declare not yet implemented
  // Enable when: map concepts implemented in Phase 9 <map> pipeline

  it.todo('fuzz_3: map frequency counter — needs cpp_map_declare concept')

  // ─── fuzz_4: set intersection ───
  // EXPECTED_DEGRADATION — cpp_set_declare not yet implemented
  // Enable when: set concepts implemented in Phase 9 <set> pipeline

  it.todo('fuzz_4: set intersection — needs cpp_set_declare concept')

  // ─── fuzz_5: BFS with queue+map+set+vector ───
  // EXPECTED_DEGRADATION — cpp_queue_declare, cpp_map_declare, cpp_set_declare not yet implemented
  // Enable when: queue/map/set concepts implemented in Phase 9

  it.todo('fuzz_5: BFS graph traversal — needs queue/map/set declare concepts')

  // ─── fuzz_7: map of vectors, group words by length ───
  // EXPECTED_DEGRADATION — cpp_map_declare not yet implemented
  // Enable when: map concepts implemented in Phase 9 <map> pipeline

  it.todo('fuzz_7: map of vectors — needs cpp_map_declare concept')

  // ─── fuzz_8: stack-queue reversal ───
  // EXPECTED_DEGRADATION — cpp_stack_declare now implemented, but still needs
  // cpp_queue_declare. Enable when: queue concepts implemented in Phase 9 <queue> pipeline

  it.todo('fuzz_8: stack-queue reversal — needs cpp_queue_declare concept')

  // ─── fuzz_9: set dedup with insert ───
  // EXPECTED_DEGRADATION — cpp_set_declare not yet implemented
  // Enable when: set concepts implemented in Phase 9 <set> pipeline

  it.todo('fuzz_9: set dedup with insert — needs cpp_set_declare concept')

  // ─── fuzz_10: sparse matrix with map<pair<int,int>,int> ───
  // EXPECTED_DEGRADATION — cpp_map_declare not yet implemented
  // Enable when: map concepts implemented in Phase 9 <map> pipeline

  it.todo('fuzz_10: sparse matrix multiplication — needs cpp_map_declare concept')
})
